/**
 * THE PERFORMANCE SANDBOX'S CAR ROSTER. GENERATED - DO NOT EDIT BY HAND.
 *
 * Written by `tools/sandbox/generateCars.mjs` (run `pnpm sandbox:cars`) from
 * `docs/design/car-performance/car-spec-book.html`, the vetted upstream for all
 * 85 cars, and the lap harness's own dimensions table.
 *
 * 26 of the 85 ship in `cars.json` and carry no model here: the sandbox reads the
 * real one. The other 59 are RESEARCH ENTRIES that are not in the game, and their
 * model is synthesised. Every physical figure on a synthesised model is the spec
 * book's own measurement, untouched. `tier` is derived from the book's roster
 * section, `tyreCompound` from the stock tyre and the build year, and the
 * layout/induction/engine tags from the book's own drivetrain, engine position
 * and aspiration - all of which the physics reads. `chassisCode`,
 * `bookValueYen`, `reliabilityBase`, `styleBase`, `styleCeiling`, `culture` and
 * the parody names are placeholders that nothing reads, which is why the
 * sandbox shows a research entry no price rather than a made-up one.
 * `aeroCeiling` is neutral rather than a placeholder: the sandbox does read it,
 * so a research entry runs a fitted aero part at exactly its authored value.
 *
 * Dev-only data. It is imported by the sandbox screen alone, which is reachable
 * only through the `import.meta.env.DEV` gate in `router/index.ts`, so a
 * production build drops this file with it.
 */
import type { CarModel } from '@midnight-garage/content'

/** Where an entry's roster tier came from: the car's real `cars.json` value, a
 * mapping derived from the in-game 26, or a judgement call on a section no
 * in-game car occupies. */
export type SandboxTierSource = 'in-game' | 'derived' | 'assigned'

export interface SandboxRosterEntry {
  id: string
  /** The spec book's roster section, e.g. `Kei`, `FR / Drift`, `Hyper wave`. */
  section: string
  /** True for the 26 cars that ship in `cars.json`. */
  inGame: boolean
  tierSource: SandboxTierSource
  /** The synthesised model, present only on the 59 research entries. An in-game
   * car's model is the real one and is read from content. */
  model?: CarModel
}

/** All 85, in spec-book order. */
export const SANDBOX_ROSTER: readonly SandboxRosterEntry[] = [
  { id: 'honda-city-e-aa', section: 'Shitbox', inGame: true, tierSource: 'in-game' },
  { id: 'suzuki-wagon-r-ct21s', section: 'Kei', inGame: true, tierSource: 'in-game' },
  { id: 'suzuki-alto-works-ha21s', section: 'Kei', inGame: true, tierSource: 'in-game' },
  { id: 'honda-civic-sir2-eg6', section: 'Fast FWD', inGame: true, tierSource: 'in-game' },
  { id: 'toyota-sprinter-trueno-ae86', section: 'FR / Drift', inGame: true, tierSource: 'in-game' },
  { id: 'nissan-silvia-ks-s14', section: 'FR / Drift', inGame: true, tierSource: 'in-game' },
  { id: 'mazda-rx7-fd3s', section: 'Rotary', inGame: true, tierSource: 'in-game' },
  { id: 'toyota-supra-rz-jza80', section: 'Flagship', inGame: true, tierSource: 'in-game' },
  { id: 'nissan-skyline-gtr-bnr32', section: 'AWD Turbo', inGame: true, tierSource: 'in-game' },
  {
    id: 'porsche-911-turbo-930',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'porsche-911-turbo-930',
      displayName: 'Porsche 911 Turbo 3.3',
      brand: 'Porsche',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['RR', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'M30/69',
        culture: 'oddball',
        yearFrom: 1982,
        yearTo: 1982,
        curbWeightKg: 1300,
        stockPowerPs: 300,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 300,
        powerRpm: 5500,
        peakTorqueNm: 412,
        torqueRpm: 4000,
        redlineRpm: 6600,
        displacementCc: 3299,
        engineConfig: 'flat-6',
        aspiration: 'turbo',
        weightDistributionFront: 40,
        wheelbaseMm: 2272,
        comHeightMm: 450,
        dragCd: 0.466,
        widthMm: 1775,
        heightMm: 1310,
        stockTyre: '225/50R16',
        tyreCompound: 'performance',
        topSpeedKmh: 252,
        lateralG97: 0.91,
        lateralG193: 0.93,
        braking97To0M: 39.7,
        braking161To0M: 100.2,
        zeroTo97S: 5.028,
        zeroTo161S: 12.002,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'honda-civic-type-r-ek9',
    section: 'Fast FWD',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'honda-civic-type-r-ek9',
      displayName: 'Honda Civic Type R',
      brand: 'Honda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'B16B',
        culture: 'oddball',
        yearFrom: 1997,
        yearTo: 1997,
        curbWeightKg: 1090,
        stockPowerPs: 185,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 185,
        powerRpm: 8200,
        peakTorqueNm: 160,
        torqueRpm: 7500,
        redlineRpm: 8400,
        displacementCc: 1595,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 62,
        wheelbaseMm: 2620,
        comHeightMm: 470,
        dragCd: 0.317,
        widthMm: 1695,
        heightMm: 1360,
        stockTyre: '195/55R15',
        tyreCompound: 'performance',
        topSpeedKmh: 243,
        lateralG97: 0.87,
        lateralG193: 0.89,
        braking97To0M: 45.5,
        braking161To0M: 114.9,
        zeroTo97S: 5.657,
        zeroTo161S: 17.28,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'honda-integra-type-r-dc2',
    section: 'Fast FWD',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'honda-integra-type-r-dc2',
      displayName: 'Acura Integra Type-R',
      brand: 'Acura',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'B18C5',
        culture: 'oddball',
        yearFrom: 2001,
        yearTo: 2001,
        curbWeightKg: 1197,
        stockPowerPs: 198,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 198,
        powerRpm: 8000,
        peakTorqueNm: 176,
        torqueRpm: 7500,
        redlineRpm: 8400,
        displacementCc: 1797,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 62,
        wheelbaseMm: 2620,
        comHeightMm: 450,
        dragCd: 0.313,
        widthMm: 1695,
        heightMm: 1330,
        stockTyre: '195/55R15',
        tyreCompound: 'performance',
        topSpeedKmh: 251,
        lateralG97: 0.9,
        lateralG193: 0.91,
        braking97To0M: 44,
        braking161To0M: 111.7,
        zeroTo97S: 6.152,
        zeroTo161S: 14.506,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  { id: 'honda-prelude-si-vtec-bb4', section: 'Fast FWD', inGame: true, tierSource: 'in-game' },
  { id: 'honda-crx-sir-ef8', section: 'Fast FWD', inGame: true, tierSource: 'in-game' },
  { id: 'honda-city-turbo-ii-aa', section: 'Fast FWD', inGame: true, tierSource: 'in-game' },
  {
    id: 'toyota-starlet-glanza-v-ep91',
    section: 'Fast FWD',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'toyota-starlet-glanza-v-ep91',
      displayName: 'Toyota Starlet Glanza V',
      brand: 'Toyota',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '4E-FTE',
        culture: 'oddball',
        yearFrom: 1996,
        yearTo: 1996,
        curbWeightKg: 950,
        stockPowerPs: 135,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 135,
        powerRpm: 6400,
        peakTorqueNm: 156,
        torqueRpm: 4800,
        redlineRpm: 7200,
        displacementCc: 1331,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 65,
        wheelbaseMm: 2300,
        comHeightMm: 450,
        dragCd: 0.3,
        widthMm: 1625,
        heightMm: 1400,
        stockTyre: '185/55R14',
        tyreCompound: 'touring',
        topSpeedKmh: 223,
        lateralG97: 0.86,
        lateralG193: 0.88,
        braking97To0M: 45.8,
        braking161To0M: 115.9,
        zeroTo97S: 7.86,
        zeroTo161S: 21.688,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  { id: 'nissan-180sx-rps13', section: 'FR / Drift', inGame: true, tierSource: 'in-game' },
  {
    id: 'toyota-chaser-tourer-v-jzx90',
    section: 'FR / Drift',
    inGame: true,
    tierSource: 'in-game',
  },
  { id: 'nissan-silvia-s13', section: 'FR / Drift', inGame: true, tierSource: 'in-game' },
  { id: 'nissan-cefiro-a31', section: 'FR / Drift', inGame: true, tierSource: 'in-game' },
  {
    id: 'nissan-laurel-c33',
    section: 'FR / Drift',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'nissan-laurel-c33',
      displayName: 'Nissan Laurel (C33)',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'RB20DET',
        culture: 'oddball',
        yearFrom: 1989,
        yearTo: 1989,
        curbWeightKg: 1350,
        stockPowerPs: 205,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 205,
        powerRpm: 6400,
        peakTorqueNm: 265,
        torqueRpm: 3200,
        redlineRpm: 7400,
        displacementCc: 1997,
        engineConfig: 'I6',
        aspiration: 'turbo',
        weightDistributionFront: 55,
        wheelbaseMm: 2670,
        comHeightMm: 540,
        dragCd: 0.33,
        widthMm: 1700,
        heightMm: 1370,
        stockTyre: '205/60R15',
        tyreCompound: 'performance',
        topSpeedKmh: 215,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'fr', 'com', 'cd'],
      },
    },
  },
  {
    id: 'toyota-chaser-tourer-v-jzx100',
    section: 'FR / Drift',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'toyota-chaser-tourer-v-jzx100',
      displayName: 'Toyota Chaser 2.5 Tourer V',
      brand: 'Toyota',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '1JZ-GTE VVT-i',
        culture: 'oddball',
        yearFrom: 1997,
        yearTo: 1997,
        curbWeightKg: 1480,
        stockPowerPs: 280,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6200,
        peakTorqueNm: 377,
        torqueRpm: 2400,
        redlineRpm: 7500,
        displacementCc: 2491,
        engineConfig: 'I6',
        aspiration: 'turbo',
        weightDistributionFront: 57,
        wheelbaseMm: 2730,
        comHeightMm: 535,
        dragCd: 0.3,
        widthMm: 1755,
        heightMm: 1400,
        stockTyre: '205/55R16',
        tyreCompound: 'performance',
        topSpeedKmh: 246,
        lateralG97: 0.89,
        lateralG193: 0.9,
        braking97To0M: 46.5,
        braking161To0M: 115.4,
        zeroTo97S: 5.852,
        zeroTo161S: 14.53,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com', 'cd'],
      },
    },
  },
  { id: 'toyota-sera-exy10', section: 'Bubble weird', inGame: true, tierSource: 'in-game' },
  {
    id: 'nissan-s-cargo-fhk11',
    section: 'Bubble weird',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'nissan-s-cargo-fhk11',
      displayName: 'Nissan S-Cargo',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'everyday',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'E15S',
        culture: 'oddball',
        yearFrom: 1989,
        yearTo: 1989,
        curbWeightKg: 950,
        stockPowerPs: 73,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 73,
        powerRpm: 5600,
        peakTorqueNm: 115,
        torqueRpm: 3200,
        redlineRpm: 6000,
        displacementCc: 1487,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 62,
        wheelbaseMm: 2260,
        comHeightMm: 700,
        dragCd: 0.513,
        widthMm: 1595,
        heightMm: 1839,
        stockTyre: '155SR13',
        tyreCompound: 'eco',
        topSpeedKmh: 139,
        lateralG97: 0.83,
        lateralG193: 0.85,
        braking97To0M: 57.6,
        zeroTo97S: 17.374,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'subaru-alcyone-svx-cxd',
    section: 'Bubble weird',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'subaru-alcyone-svx-cxd',
      displayName: 'Subaru SVX',
      brand: 'Subaru',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'everyday',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'EG33',
        culture: 'oddball',
        yearFrom: 1996,
        yearTo: 1996,
        curbWeightKg: 1624,
        stockPowerPs: 233,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 233,
        powerRpm: 6000,
        peakTorqueNm: 309,
        torqueRpm: 4400,
        redlineRpm: 6600,
        displacementCc: 3318,
        engineConfig: 'flat-6',
        aspiration: 'NA',
        weightDistributionFront: 59,
        wheelbaseMm: 2610,
        comHeightMm: 500,
        dragCd: 0.35,
        widthMm: 1770,
        heightMm: 1310,
        stockTyre: '225/50R16',
        tyreCompound: 'sport',
        topSpeedKmh: 252,
        lateralG97: 0.88,
        lateralG193: 0.89,
        braking97To0M: 41.6,
        braking161To0M: 108.8,
        zeroTo97S: 7.209,
        zeroTo161S: 18.004,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'mitsubishi-gto-twin-turbo-z16a',
    section: 'Flagship',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'mitsubishi-gto-twin-turbo-z16a',
      displayName: 'Mitsubishi GTO',
      brand: 'Mitsubishi',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '6G72TT',
        culture: 'oddball',
        yearFrom: 1997,
        yearTo: 1997,
        curbWeightKg: 1680,
        stockPowerPs: 324,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6000,
        peakTorqueNm: 427,
        torqueRpm: 2500,
        redlineRpm: 7000,
        displacementCc: 2972,
        engineConfig: 'V6',
        aspiration: 'twin-turbo',
        weightDistributionFront: 61,
        wheelbaseMm: 2470,
        comHeightMm: 480,
        dragCd: 0.405,
        widthMm: 1840,
        heightMm: 1285,
        stockTyre: '235/45R17',
        tyreCompound: 'sport',
        topSpeedKmh: 268,
        lateralG97: 0.89,
        lateralG193: 0.91,
        braking97To0M: 42.4,
        braking161To0M: 107.1,
        zeroTo97S: 5.611,
        zeroTo161S: 14.223,
        measuredFrom: 'forza-panel',
        dataConfidence: 'LOW',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'mitsubishi-starion-a187a',
    section: 'Flagship',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'mitsubishi-starion-a187a',
      displayName: 'Mitsubishi Starion (A187A)',
      brand: 'Mitsubishi',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'G54B',
        culture: 'oddball',
        yearFrom: 1988,
        yearTo: 1988,
        curbWeightKg: 1320,
        stockPowerPs: 175,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 175,
        powerRpm: 5000,
        peakTorqueNm: 314,
        torqueRpm: 3000,
        redlineRpm: 6000,
        displacementCc: 2555,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 55,
        wheelbaseMm: 2435,
        comHeightMm: 470,
        dragCd: 0.37,
        widthMm: 1745,
        heightMm: 1275,
        stockTyre: '205/55R16',
        tyreCompound: 'performance',
        zeroToHundredS: 8.2,
        topSpeedKmh: 215,
        measuredFrom: 'modelled',
        dataConfidence: 'LOW',
        estimatedFields: ['rl', 'fr', 'com'],
      },
    },
  },
  {
    id: 'toyota-soarer-jzz30',
    section: 'Flagship',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'toyota-soarer-jzz30',
      displayName: 'Toyota Soarer 2.5 GT-T',
      brand: 'Toyota',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '1JZ-GTE',
        culture: 'oddball',
        yearFrom: 1997,
        yearTo: 1997,
        curbWeightKg: 1570,
        stockPowerPs: 280,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6200,
        peakTorqueNm: 378,
        torqueRpm: 4800,
        redlineRpm: 7000,
        displacementCc: 2491,
        engineConfig: 'I6',
        aspiration: 'twin-turbo',
        weightDistributionFront: 53,
        wheelbaseMm: 2690,
        comHeightMm: 480,
        dragCd: 0.331,
        widthMm: 1790,
        heightMm: 1340,
        stockTyre: '225/55R16',
        tyreCompound: 'sport',
        topSpeedKmh: 271,
        lateralG97: 0.88,
        lateralG193: 0.88,
        braking97To0M: 46.1,
        braking161To0M: 115.1,
        zeroTo97S: 6.924,
        zeroTo161S: 15.834,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'nissan-fairlady-240zg-hs30',
    section: 'Kyusha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-fairlady-240zg-hs30',
      displayName: 'Nissan Fairlady 240ZG (HS30)',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'L24',
        culture: 'oddball',
        yearFrom: 1971,
        yearTo: 1971,
        curbWeightKg: 1010,
        stockPowerPs: 150,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 150,
        powerRpm: 5600,
        peakTorqueNm: 206,
        torqueRpm: 4800,
        redlineRpm: 7000,
        displacementCc: 2393,
        engineConfig: 'I6',
        aspiration: 'NA',
        weightDistributionFront: 51,
        wheelbaseMm: 2305,
        comHeightMm: 460,
        dragCd: 0.39,
        widthMm: 1690,
        heightMm: 1285,
        stockTyre: '175HR14',
        tyreCompound: 'touring',
        topSpeedKmh: 210,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'fr', 'com'],
      },
    },
  },
  {
    id: 'datsun-510-bluebird-pl510',
    section: 'Kyusha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'datsun-510-bluebird-pl510',
      displayName: 'Datsun 510',
      brand: 'Datsun',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'L16',
        culture: 'oddball',
        yearFrom: 1970,
        yearTo: 1970,
        curbWeightKg: 965,
        stockPowerPs: 97,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 97,
        powerRpm: 5600,
        peakTorqueNm: 136,
        torqueRpm: 3600,
        redlineRpm: 6500,
        displacementCc: 1595,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 54,
        wheelbaseMm: 2420,
        comHeightMm: 520,
        dragCd: 0.53,
        widthMm: 1560,
        heightMm: 1405,
        stockTyre: '5.60-13',
        tyreCompound: 'eco',
        topSpeedKmh: 167,
        lateralG97: 0.73,
        lateralG193: 0.73,
        braking97To0M: 56.8,
        braking161To0M: 137.4,
        zeroTo97S: 13.409,
        zeroTo161S: 41.283,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'nissan-skyline-2000gt-x-kenmeri-kgc110',
    section: 'Kyusha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-skyline-2000gt-x-kenmeri-kgc110',
      displayName: 'Nissan Skyline H/T 2000GT-R',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'S20',
        culture: 'oddball',
        yearFrom: 1973,
        yearTo: 1973,
        curbWeightKg: 1145,
        stockPowerPs: 160,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 160,
        powerRpm: 7000,
        peakTorqueNm: 176,
        torqueRpm: 5600,
        redlineRpm: 8000,
        displacementCc: 1989,
        engineConfig: 'I6',
        aspiration: 'NA',
        weightDistributionFront: 55,
        wheelbaseMm: 2610,
        comHeightMm: 530,
        dragCd: 0.458,
        widthMm: 1595,
        heightMm: 1375,
        stockTyre: '6.45S-14',
        tyreCompound: 'eco',
        topSpeedKmh: 208,
        lateralG97: 0.81,
        lateralG193: 0.81,
        braking97To0M: 50.2,
        braking161To0M: 122.5,
        zeroTo97S: 8.917,
        zeroTo161S: 22.802,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'mazda-cosmo-sport-110s-l10a',
    section: 'Kyusha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'mazda-cosmo-sport-110s-l10a',
      displayName: 'Mazda Cosmo 110S Series II',
      brand: 'Mazda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Rotary'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '10A',
        culture: 'oddball',
        yearFrom: 1972,
        yearTo: 1972,
        curbWeightKg: 940,
        stockPowerPs: 110,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 110,
        powerRpm: 7000,
        peakTorqueNm: 130,
        torqueRpm: 3500,
        redlineRpm: 7000,
        displacementCc: 982,
        engineConfig: 'rotary-2',
        aspiration: 'NA',
        weightDistributionFront: 51,
        wheelbaseMm: 2200,
        comHeightMm: 440,
        dragCd: 0.38,
        widthMm: 1595,
        heightMm: 1165,
        stockTyre: '165SR14',
        tyreCompound: 'touring',
        zeroToHundredS: 8.7,
        topSpeedKmh: 185,
        measuredFrom: 'modelled',
        dataConfidence: 'HIGH',
        estimatedFields: ['fr', 'com', 'cd'],
      },
    },
  },
  {
    id: 'mercedes-190e-2-5-16-evo-ii-w201',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'mercedes-190e-2-5-16-evo-ii-w201',
      displayName: 'Mercedes-Benz 190E 2.5-16 Evolution II',
      brand: 'Mercedes-Benz',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'M102',
        culture: 'oddball',
        yearFrom: 1990,
        yearTo: 1990,
        curbWeightKg: 1340,
        stockPowerPs: 238,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 238,
        powerRpm: 7200,
        peakTorqueNm: 245,
        torqueRpm: 5500,
        redlineRpm: 7700,
        displacementCc: 2463,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 53,
        wheelbaseMm: 2665,
        comHeightMm: 500,
        dragCd: 0.292,
        widthMm: 1720,
        heightMm: 1342,
        stockTyre: '245/40R17',
        tyreCompound: 'sport',
        topSpeedKmh: 271,
        lateralG97: 0.88,
        lateralG193: 0.88,
        braking97To0M: 45.1,
        braking161To0M: 112.8,
        zeroTo97S: 7.024,
        zeroTo161S: 17.75,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'bmw-m3-e30',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'bmw-m3-e30',
      displayName: 'BMW M3',
      brand: 'BMW',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'S14',
        culture: 'oddball',
        yearFrom: 1988,
        yearTo: 1988,
        curbWeightKg: 1253,
        stockPowerPs: 195,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 195,
        powerRpm: 6750,
        peakTorqueNm: 230,
        torqueRpm: 4750,
        redlineRpm: 7250,
        displacementCc: 2302,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 51,
        wheelbaseMm: 2562,
        comHeightMm: 460,
        dragCd: 0.304,
        widthMm: 1680,
        heightMm: 1370,
        stockTyre: '205/55R15',
        tyreCompound: 'performance',
        topSpeedKmh: 250,
        lateralG97: 0.89,
        lateralG193: 0.91,
        braking97To0M: 46.5,
        braking161To0M: 114.8,
        zeroTo97S: 6.784,
        zeroTo161S: 19.323,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'lancia-delta-hf-integrale-evo',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'lancia-delta-hf-integrale-evo',
      displayName: 'Lancia Delta HF Integrale Evo',
      brand: 'Lancia',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '831',
        culture: 'oddball',
        yearFrom: 1992,
        yearTo: 1992,
        curbWeightKg: 1300,
        stockPowerPs: 213,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 213,
        powerRpm: 5750,
        peakTorqueNm: 304,
        torqueRpm: 3500,
        redlineRpm: 6500,
        displacementCc: 1995,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 63,
        wheelbaseMm: 2480,
        comHeightMm: 500,
        dragCd: 0.478,
        widthMm: 1770,
        heightMm: 1365,
        stockTyre: '205/50R15',
        tyreCompound: 'performance',
        topSpeedKmh: 219,
        lateralG97: 0.91,
        lateralG193: 0.92,
        braking97To0M: 42.4,
        braking161To0M: 107,
        zeroTo97S: 5.926,
        zeroTo161S: 17.202,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'alfa-romeo-75-3-0-v6',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'alfa-romeo-75-3-0-v6',
      displayName: 'Alfa Romeo 75 3.0 V6',
      brand: 'Alfa',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'AR06',
        culture: 'oddball',
        yearFrom: 1987,
        yearTo: 1987,
        curbWeightKg: 1250,
        stockPowerPs: 188,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 188,
        powerRpm: 5800,
        peakTorqueNm: 245,
        torqueRpm: 4000,
        redlineRpm: 6200,
        displacementCc: 2959,
        engineConfig: 'V6',
        aspiration: 'NA',
        weightDistributionFront: 55,
        wheelbaseMm: 2510,
        comHeightMm: 520,
        dragCd: 0.34,
        widthMm: 1631,
        heightMm: 1349,
        stockTyre: '195/60R14',
        tyreCompound: 'performance',
        topSpeedKmh: 220,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'ferrari-testarossa-f113',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'ferrari-testarossa-f113',
      displayName: 'Ferrari 512 TR',
      brand: 'Ferrari',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['MR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'F113G',
        culture: 'oddball',
        yearFrom: 1992,
        yearTo: 1992,
        curbWeightKg: 1674,
        stockPowerPs: 427,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 427,
        powerRpm: 6750,
        peakTorqueNm: 488,
        torqueRpm: 5500,
        redlineRpm: 7250,
        displacementCc: 4943,
        aspiration: 'NA',
        weightDistributionFront: 42,
        wheelbaseMm: 2550,
        comHeightMm: 480,
        dragCd: 0.344,
        widthMm: 1976,
        heightMm: 1130,
        stockTyre: '255/50R16',
        tyreCompound: 'sport',
        topSpeedKmh: 317,
        lateralG97: 1.07,
        lateralG193: 1.11,
        braking97To0M: 37.4,
        braking161To0M: 92.7,
        zeroTo97S: 4.917,
        zeroTo161S: 10.519,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com', 'rl'],
      },
    },
  },
  {
    id: 'lamborghini-countach-lp5000-qv',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'lamborghini-countach-lp5000-qv',
      displayName: 'Lamborghini Countach LP5000 QV',
      brand: 'Lamborghini',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['MR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'LP112D',
        culture: 'oddball',
        yearFrom: 1988,
        yearTo: 1988,
        curbWeightKg: 1490,
        stockPowerPs: 461,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 461,
        powerRpm: 7000,
        peakTorqueNm: 500,
        torqueRpm: 5200,
        redlineRpm: 7300,
        displacementCc: 5167,
        engineConfig: 'V12',
        aspiration: 'NA',
        weightDistributionFront: 41,
        wheelbaseMm: 2450,
        comHeightMm: 450,
        dragCd: 0.465,
        widthMm: 2000,
        heightMm: 1070,
        stockTyre: '345/35R15',
        tyreCompound: 'performance',
        topSpeedKmh: 300,
        lateralG97: 1.1,
        lateralG193: 1.15,
        braking97To0M: 39.3,
        braking161To0M: 96.3,
        zeroTo97S: 4.839,
        zeroTo161S: 11.699,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'rover-mini-cooper-1-3i',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'rover-mini-cooper-1-3i',
      displayName: 'MINI Cooper S',
      brand: 'MINI',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['FF', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'A-series',
        culture: 'oddball',
        yearFrom: 1965,
        yearTo: 1965,
        curbWeightKg: 671,
        stockPowerPs: 76,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 76,
        powerRpm: 5800,
        peakTorqueNm: 108,
        torqueRpm: 3000,
        redlineRpm: 6000,
        displacementCc: 1275,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 60,
        wheelbaseMm: 2035,
        comHeightMm: 480,
        dragCd: 0.543,
        widthMm: 1440,
        heightMm: 1340,
        stockTyre: '145/70R12',
        tyreCompound: 'eco',
        topSpeedKmh: 160,
        lateralG97: 0.75,
        lateralG193: 0.74,
        braking97To0M: 52.4,
        zeroTo97S: 10.387,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'ferrari-f355-berlinetta-f129',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'ferrari-f355-berlinetta-f129',
      displayName: 'Ferrari F355 Berlinetta',
      brand: 'Ferrari',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['MR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'F129B',
        culture: 'oddball',
        yearFrom: 1994,
        yearTo: 1994,
        curbWeightKg: 1450,
        stockPowerPs: 380,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 380,
        powerRpm: 8250,
        peakTorqueNm: 363,
        torqueRpm: 6000,
        redlineRpm: 8500,
        displacementCc: 3496,
        engineConfig: 'V8',
        aspiration: 'NA',
        weightDistributionFront: 41,
        wheelbaseMm: 2451,
        comHeightMm: 480,
        dragCd: 0.365,
        widthMm: 1900,
        heightMm: 1170,
        stockTyre: '265/40R18',
        tyreCompound: 'sport',
        topSpeedKmh: 300,
        lateralG97: 1.07,
        lateralG193: 1.12,
        braking97To0M: 38.4,
        braking161To0M: 95.3,
        zeroTo97S: 4.747,
        zeroTo161S: 10.939,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'bmw-m3-e36',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'bmw-m3-e36',
      displayName: 'BMW M3',
      brand: 'BMW',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'S50B32',
        culture: 'oddball',
        yearFrom: 1997,
        yearTo: 1997,
        curbWeightKg: 1460,
        stockPowerPs: 325,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 325,
        powerRpm: 7400,
        peakTorqueNm: 350,
        torqueRpm: 3250,
        redlineRpm: 7600,
        displacementCc: 3201,
        engineConfig: 'I6',
        aspiration: 'NA',
        weightDistributionFront: 50,
        wheelbaseMm: 2700,
        comHeightMm: 510,
        dragCd: 0.363,
        widthMm: 1710,
        heightMm: 1335,
        stockTyre: '235/40R17',
        tyreCompound: 'sport',
        topSpeedKmh: 282,
        lateralG97: 0.92,
        lateralG193: 0.93,
        braking97To0M: 44,
        braking161To0M: 108.7,
        zeroTo97S: 5.249,
        zeroTo161S: 12.056,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'ford-escort-rs-cosworth',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'ford-escort-rs-cosworth',
      displayName: 'Ford Escort RS Cosworth',
      brand: 'Ford',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'YBT',
        culture: 'oddball',
        yearFrom: 1992,
        yearTo: 1992,
        curbWeightKg: 1275,
        stockPowerPs: 227,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 227,
        powerRpm: 6250,
        peakTorqueNm: 304,
        torqueRpm: 3500,
        redlineRpm: 6800,
        displacementCc: 1993,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 56,
        wheelbaseMm: 2551,
        comHeightMm: 540,
        dragCd: 0.437,
        widthMm: 1738,
        heightMm: 1405,
        stockTyre: '245/45R16',
        tyreCompound: 'sport',
        topSpeedKmh: 230,
        lateralG97: 0.89,
        lateralG193: 0.9,
        braking97To0M: 43.2,
        braking161To0M: 110.4,
        zeroTo97S: 6.111,
        zeroTo161S: 17.214,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'vw-golf-gti-mk2-16v',
    section: 'Gaisha',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'vw-golf-gti-mk2-16v',
      displayName: 'Volkswagen Golf GTI 16V Mk2',
      brand: 'Volkswagen',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'gaisha',
      tags: ['FF', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'KR',
        culture: 'oddball',
        yearFrom: 1992,
        yearTo: 1992,
        curbWeightKg: 1100,
        stockPowerPs: 141,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 141,
        powerRpm: 6100,
        peakTorqueNm: 163,
        torqueRpm: 4600,
        redlineRpm: 7000,
        displacementCc: 1781,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 63,
        wheelbaseMm: 2475,
        comHeightMm: 530,
        dragCd: 0.384,
        widthMm: 1680,
        heightMm: 1400,
        stockTyre: '185/60R14',
        tyreCompound: 'touring',
        topSpeedKmh: 206,
        lateralG97: 0.81,
        lateralG193: 0.8,
        braking97To0M: 48.7,
        braking161To0M: 124.1,
        zeroTo97S: 8.032,
        zeroTo161S: 23.48,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com'],
      },
    },
  },
  { id: 'mazda-savanna-rx7-fc3s', section: 'Rotary', inGame: true, tierSource: 'in-game' },
  {
    id: 'eunos-cosmo-jc',
    section: 'Rotary',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'eunos-cosmo-jc',
      displayName: 'Eunos Cosmo (JC)',
      brand: 'Eunos',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Rotary'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '20B-REW',
        culture: 'oddball',
        yearFrom: 1990,
        yearTo: 1990,
        curbWeightKg: 1620,
        stockPowerPs: 300,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6500,
        peakTorqueNm: 402,
        torqueRpm: 3000,
        redlineRpm: 7000,
        displacementCc: 1962,
        engineConfig: 'rotary-3',
        aspiration: 'twin-turbo',
        weightDistributionFront: 55,
        wheelbaseMm: 2750,
        comHeightMm: 500,
        dragCd: 0.28,
        widthMm: 1795,
        heightMm: 1305,
        stockTyre: '215/60R15',
        tyreCompound: 'performance',
        topSpeedKmh: 250,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['ps', 'fr', 'com', 'cd'],
      },
    },
  },
  { id: 'subaru-impreza-wrx-sti-gc8', section: 'AWD Turbo', inGame: true, tierSource: 'in-game' },
  {
    id: 'toyota-celica-gt-four-st205',
    section: 'AWD Turbo',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'toyota-celica-gt-four-st205',
      displayName: 'Toyota Celica GT-Four ST205',
      brand: 'Toyota',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '3S-GTE',
        culture: 'oddball',
        yearFrom: 1994,
        yearTo: 1994,
        curbWeightKg: 1440,
        stockPowerPs: 259,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 259,
        powerRpm: 6000,
        peakTorqueNm: 304,
        torqueRpm: 4000,
        redlineRpm: 7000,
        displacementCc: 1998,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 60,
        wheelbaseMm: 2535,
        comHeightMm: 470,
        dragCd: 0.338,
        widthMm: 1750,
        heightMm: 1305,
        stockTyre: '215/50R16',
        tyreCompound: 'performance',
        topSpeedKmh: 266.8,
        lateralG97: 0.86,
        lateralG193: 0.86,
        braking97To0M: 42.8,
        braking161To0M: 111.7,
        zeroTo97S: 5.87,
        zeroTo161S: 16.824,
        measuredFrom: 'forza-panel-override',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'nissan-pulsar-gti-r-rnn14',
    section: 'AWD Turbo',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'nissan-pulsar-gti-r-rnn14',
      displayName: 'Nissan Pulsar GTI-R',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'SR20DET',
        culture: 'oddball',
        yearFrom: 1990,
        yearTo: 1990,
        curbWeightKg: 1240,
        stockPowerPs: 230,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 230,
        powerRpm: 6400,
        peakTorqueNm: 283,
        torqueRpm: 4800,
        redlineRpm: 7500,
        displacementCc: 1998,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 62,
        wheelbaseMm: 2430,
        comHeightMm: 460,
        dragCd: 0.384,
        widthMm: 1690,
        heightMm: 1410,
        stockTyre: '195/55R14',
        tyreCompound: 'performance',
        topSpeedKmh: 243,
        lateralG97: 0.86,
        lateralG193: 0.86,
        braking97To0M: 45,
        braking161To0M: 116.3,
        zeroTo97S: 4.928,
        zeroTo161S: 13.931,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'mazda-familia-gt-r-bg8z',
    section: 'AWD Turbo',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'mazda-familia-gt-r-bg8z',
      displayName: 'Mazda Familia GT-R (BG8Z)',
      brand: 'Mazda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'BPD',
        culture: 'oddball',
        yearFrom: 1992,
        yearTo: 1992,
        curbWeightKg: 1210,
        stockPowerPs: 210,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 210,
        powerRpm: 6000,
        peakTorqueNm: 250,
        torqueRpm: 4500,
        redlineRpm: 7000,
        displacementCc: 1839,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 60,
        wheelbaseMm: 2450,
        comHeightMm: 460,
        dragCd: 0.32,
        widthMm: 1690,
        heightMm: 1390,
        stockTyre: '195/50R15',
        tyreCompound: 'performance',
        zeroToHundredS: 6.2,
        topSpeedKmh: 230,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'fr', 'com', 'cd'],
      },
    },
  },
  {
    id: 'nissan-350z-z33',
    section: '2004+ wave',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-350z-z33',
      displayName: 'Nissan Fairlady Z',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'VQ35DE',
        culture: 'oddball',
        yearFrom: 2003,
        yearTo: 2003,
        curbWeightKg: 1501,
        stockPowerPs: 291,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6200,
        peakTorqueNm: 370,
        torqueRpm: 4800,
        redlineRpm: 7000,
        displacementCc: 3498,
        engineConfig: 'V6',
        aspiration: 'NA',
        weightDistributionFront: 53,
        wheelbaseMm: 2650,
        comHeightMm: 510,
        dragCd: 0.301,
        widthMm: 1815,
        heightMm: 1315,
        stockTyre: '235/50R17',
        tyreCompound: 'sport',
        topSpeedKmh: 284,
        lateralG97: 0.93,
        lateralG193: 0.95,
        braking97To0M: 43.9,
        braking161To0M: 109.2,
        zeroTo97S: 5.749,
        zeroTo161S: 14.258,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'mazda-rx-8-se3p',
    section: '2004+ wave',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'mazda-rx-8-se3p',
      displayName: 'Mazda RX-8 R3',
      brand: 'Mazda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Rotary'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '13B-MSP',
        culture: 'oddball',
        yearFrom: 2011,
        yearTo: 2011,
        curbWeightKg: 1390,
        stockPowerPs: 235,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 235,
        powerRpm: 8200,
        peakTorqueNm: 216,
        torqueRpm: 5500,
        redlineRpm: 9000,
        displacementCc: 1308,
        engineConfig: 'rotary-2',
        aspiration: 'NA',
        weightDistributionFront: 52,
        wheelbaseMm: 2703,
        comHeightMm: 480,
        dragCd: 0.354,
        widthMm: 1770,
        heightMm: 1340,
        stockTyre: '225/45R18',
        tyreCompound: 'sport',
        topSpeedKmh: 251,
        lateralG97: 0.93,
        lateralG193: 0.95,
        braking97To0M: 44.5,
        braking161To0M: 109.2,
        zeroTo97S: 5.884,
        zeroTo161S: 15.863,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'mitsubishi-lancer-evo-viii-mr-ct9a',
    section: '2004+ wave',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'mitsubishi-lancer-evo-viii-mr-ct9a',
      displayName: 'Mitsubishi Lancer Evolution VIII MR',
      brand: 'Mitsubishi',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '4G63T',
        culture: 'oddball',
        yearFrom: 2004,
        yearTo: 2004,
        curbWeightKg: 1410,
        stockPowerPs: 309,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6500,
        peakTorqueNm: 427,
        torqueRpm: 3500,
        redlineRpm: 7000,
        displacementCc: 1997,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 60,
        wheelbaseMm: 2625,
        comHeightMm: 480,
        dragCd: 0.343,
        widthMm: 1770,
        heightMm: 1450,
        stockTyre: '235/45R17',
        tyreCompound: 'sport',
        activeYaw: 'ayc',
        topSpeedKmh: 272,
        lateralG97: 0.92,
        lateralG193: 0.93,
        braking97To0M: 40.9,
        braking161To0M: 105,
        zeroTo97S: 4.728,
        zeroTo161S: 12.436,
        measuredFrom: 'forza-panel',
        dataConfidence: 'LOW',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'honda-integra-type-r-dc5',
    section: '2004+ wave',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'honda-integra-type-r-dc5',
      displayName: 'Acura RSX Type-S',
      brand: 'Acura',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'K20A2',
        culture: 'oddball',
        yearFrom: 2002,
        yearTo: 2002,
        curbWeightKg: 1279,
        stockPowerPs: 203,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 203,
        powerRpm: 7400,
        peakTorqueNm: 193,
        torqueRpm: 6000,
        redlineRpm: 7900,
        displacementCc: 1998,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 61,
        wheelbaseMm: 2570,
        comHeightMm: 450,
        dragCd: 0.351,
        widthMm: 1725,
        heightMm: 1385,
        stockTyre: '215/45R17',
        tyreCompound: 'performance',
        topSpeedKmh: 239,
        lateralG97: 0.9,
        lateralG193: 0.92,
        braking97To0M: 43.3,
        braking161To0M: 109.6,
        zeroTo97S: 6.666,
        zeroTo161S: 17.778,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'daihatsu-copen-l880k',
    section: 'Kei',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'daihatsu-copen-l880k',
      displayName: 'Daihatsu Copen (L880K)',
      brand: 'Daihatsu',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'entry',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'Turbo', 'Piston', 'Kei'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'JB-DET',
        culture: 'oddball',
        yearFrom: 2002,
        yearTo: 2002,
        curbWeightKg: 810,
        stockPowerPs: 64,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 64,
        powerRpm: 6000,
        peakTorqueNm: 110,
        torqueRpm: 3200,
        redlineRpm: 6500,
        displacementCc: 659,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 60,
        wheelbaseMm: 2230,
        comHeightMm: 450,
        dragCd: 0.32,
        widthMm: 1475,
        heightMm: 1245,
        stockTyre: '165/50R15',
        tyreCompound: 'touring',
        zeroToHundredS: 11.7,
        topSpeedKmh: 150,
        measuredFrom: 'modelled',
        dataConfidence: 'LOW',
        estimatedFields: ['rl', 'fr', 'com', 'cd'],
      },
    },
  },
  {
    id: 'nissan-gt-r-r35',
    section: 'Hyper wave',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-gt-r-r35',
      displayName: 'Nissan GT-R Black Edition (R35)',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'VR38DETT',
        culture: 'oddball',
        yearFrom: 2012,
        yearTo: 2012,
        curbWeightKg: 1763,
        stockPowerPs: 550,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 550,
        powerRpm: 6400,
        peakTorqueNm: 632,
        torqueRpm: 4400,
        redlineRpm: 7100,
        displacementCc: 3799,
        engineConfig: 'V6',
        aspiration: 'twin-turbo',
        weightDistributionFront: 55,
        wheelbaseMm: 2780,
        comHeightMm: 470,
        dragCd: 0.309,
        widthMm: 1895,
        heightMm: 1370,
        stockTyre: '285/35R20',
        tyreCompound: 'grand',
        activeYaw: 'attesa',
        topSpeedKmh: 341,
        lateralG97: 1.07,
        lateralG193: 1.13,
        braking97To0M: 32.5,
        braking161To0M: 81.7,
        zeroTo97S: 2.754,
        zeroTo161S: 6.864,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'lexus-lfa',
    section: 'Hyper wave',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'lexus-lfa',
      displayName: 'Lexus LFA',
      brand: 'Lexus',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '1LR-GUE',
        culture: 'oddball',
        yearFrom: 2010,
        yearTo: 2010,
        curbWeightKg: 1480,
        stockPowerPs: 560,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 560,
        powerRpm: 8700,
        peakTorqueNm: 480,
        torqueRpm: 6800,
        redlineRpm: 9000,
        displacementCc: 4805,
        engineConfig: 'V10',
        aspiration: 'NA',
        weightDistributionFront: 48,
        wheelbaseMm: 2605,
        comHeightMm: 460,
        dragCd: 0.31,
        widthMm: 1895,
        heightMm: 1220,
        stockTyre: '305/30R20',
        tyreCompound: 'grand',
        topSpeedKmh: 327,
        lateralG97: 1.03,
        lateralG193: 1.09,
        braking97To0M: 30.9,
        braking161To0M: 73.5,
        zeroTo97S: 3.66,
        zeroTo161S: 7.694,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'nissan-skyline-gt-r-v-spec-ii-bnr34',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-skyline-gt-r-v-spec-ii-bnr34',
      displayName: 'Nissan Skyline GT-R V-Spec II',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'RB26DETT',
        culture: 'oddball',
        yearFrom: 2000,
        yearTo: 2000,
        curbWeightKg: 1560,
        stockPowerPs: 285,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6800,
        peakTorqueNm: 392,
        torqueRpm: 4400,
        redlineRpm: 8000,
        displacementCc: 2568,
        engineConfig: 'I6',
        aspiration: 'twin-turbo',
        weightDistributionFront: 55,
        wheelbaseMm: 2665,
        comHeightMm: 470,
        dragCd: 0.292,
        widthMm: 1785,
        heightMm: 1360,
        stockTyre: '245/40R18',
        tyreCompound: 'sport',
        activeYaw: 'attesa',
        topSpeedKmh: 283,
        lateralG97: 0.92,
        lateralG193: 0.96,
        braking97To0M: 41.6,
        braking161To0M: 103.8,
        zeroTo97S: 4.546,
        zeroTo161S: 10.571,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'honda-nsx-r-na1',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'honda-nsx-r-na1',
      displayName: 'Honda NSX-R',
      brand: 'Honda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['MR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'C30A',
        culture: 'oddball',
        yearFrom: 1992,
        yearTo: 1992,
        curbWeightKg: 1230,
        stockPowerPs: 280,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 7300,
        peakTorqueNm: 294,
        torqueRpm: 5400,
        redlineRpm: 8000,
        displacementCc: 2977,
        engineConfig: 'V6',
        aspiration: 'NA',
        weightDistributionFront: 42,
        wheelbaseMm: 2530,
        comHeightMm: 450,
        dragCd: 0.365,
        widthMm: 1810,
        heightMm: 1170,
        stockTyre: '225/50R16',
        tyreCompound: 'sport',
        topSpeedKmh: 275,
        lateralG97: 1.07,
        lateralG193: 1.13,
        braking97To0M: 38.7,
        braking161To0M: 95.6,
        zeroTo97S: 4.632,
        zeroTo161S: 11.46,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'nissan-skyline-gt-r-hakosuka-kpgc10',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-skyline-gt-r-hakosuka-kpgc10',
      displayName: 'Nissan Skyline 2000GT-R',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'S20',
        culture: 'oddball',
        yearFrom: 1971,
        yearTo: 1971,
        curbWeightKg: 1100,
        stockPowerPs: 162,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 162,
        powerRpm: 7000,
        peakTorqueNm: 180,
        torqueRpm: 5600,
        redlineRpm: 8000,
        displacementCc: 1989,
        engineConfig: 'I6',
        aspiration: 'NA',
        weightDistributionFront: 54,
        wheelbaseMm: 2570,
        comHeightMm: 500,
        dragCd: 0.416,
        widthMm: 1665,
        heightMm: 1370,
        stockTyre: '6.45H14',
        tyreCompound: 'eco',
        topSpeedKmh: 213,
        lateralG97: 0.79,
        lateralG193: 0.79,
        braking97To0M: 52.4,
        braking161To0M: 129.4,
        zeroTo97S: 6.936,
        zeroTo161S: 19.706,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'nissan-fairlady-z432-ps30',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-fairlady-z432-ps30',
      displayName: 'Nissan Fairlady Z 432',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'S20',
        culture: 'oddball',
        yearFrom: 1969,
        yearTo: 1969,
        curbWeightKg: 1047,
        stockPowerPs: 162,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 162,
        powerRpm: 7000,
        peakTorqueNm: 180,
        torqueRpm: 5600,
        redlineRpm: 8000,
        displacementCc: 1989,
        engineConfig: 'I6',
        aspiration: 'NA',
        weightDistributionFront: 51,
        wheelbaseMm: 2305,
        comHeightMm: 480,
        dragCd: 0.42,
        widthMm: 1630,
        heightMm: 1290,
        stockTyre: '155HR14',
        tyreCompound: 'eco',
        topSpeedKmh: 199,
        lateralG97: 0.81,
        lateralG193: 0.8,
        braking97To0M: 51.7,
        braking161To0M: 127,
        zeroTo97S: 8.62,
        zeroTo161S: 26.714,
        measuredFrom: 'forza-panel',
        dataConfidence: 'LOW',
        estimatedFields: ['rl', 'com', 'cd'],
      },
    },
  },
  {
    id: 'subaru-impreza-22b-sti',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'subaru-impreza-22b-sti',
      displayName: 'Subaru Impreza 22B-STi Version',
      brand: 'Subaru',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'EJ22',
        culture: 'oddball',
        yearFrom: 1998,
        yearTo: 1998,
        curbWeightKg: 1270,
        stockPowerPs: 280,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6000,
        peakTorqueNm: 359,
        torqueRpm: 3200,
        redlineRpm: 7000,
        displacementCc: 2212,
        engineConfig: 'flat-4',
        aspiration: 'turbo',
        weightDistributionFront: 58,
        wheelbaseMm: 2520,
        comHeightMm: 460,
        dragCd: 0.364,
        widthMm: 1770,
        heightMm: 1390,
        stockTyre: '235/40R17',
        tyreCompound: 'sport',
        topSpeedKmh: 262,
        lateralG97: 0.95,
        lateralG193: 1,
        braking97To0M: 39.8,
        braking161To0M: 102,
        zeroTo97S: 4.534,
        zeroTo161S: 12.789,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'mitsubishi-lancer-evo-vi-tommi-makinen-cp9a',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'mitsubishi-lancer-evo-vi-tommi-makinen-cp9a',
      displayName: 'Mitsubishi Lancer Evolution VI GSR TM Edition',
      brand: 'Mitsubishi',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '4G63T',
        culture: 'oddball',
        yearFrom: 2001,
        yearTo: 2001,
        curbWeightKg: 1280,
        stockPowerPs: 280,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6500,
        peakTorqueNm: 373,
        torqueRpm: 2750,
        redlineRpm: 7000,
        displacementCc: 1997,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 58,
        wheelbaseMm: 2510,
        comHeightMm: 470,
        dragCd: 0.34,
        widthMm: 1770,
        heightMm: 1405,
        stockTyre: '225/45R17',
        tyreCompound: 'sport',
        activeYaw: 'ayc',
        topSpeedKmh: 240,
        lateralG97: 0.95,
        lateralG193: 1.03,
        braking97To0M: 40.6,
        braking161To0M: 101.6,
        zeroTo97S: 4.52,
        zeroTo161S: 9.65,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com', 'cd'],
      },
    },
  },
  {
    id: 'toyota-2000gt-mf10',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'toyota-2000gt-mf10',
      displayName: 'Toyota 2000GT',
      brand: 'Toyota',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '3M',
        culture: 'oddball',
        yearFrom: 1969,
        yearTo: 1969,
        curbWeightKg: 1157,
        stockPowerPs: 152,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 152,
        powerRpm: 6600,
        peakTorqueNm: 176,
        torqueRpm: 5000,
        redlineRpm: 7000,
        displacementCc: 1988,
        engineConfig: 'I6',
        aspiration: 'NA',
        weightDistributionFront: 51,
        wheelbaseMm: 2330,
        comHeightMm: 470,
        dragCd: 0.28,
        widthMm: 1600,
        heightMm: 1160,
        stockTyre: '165R15',
        tyreCompound: 'touring',
        topSpeedKmh: 228,
        lateralG97: 0.79,
        lateralG193: 0.79,
        braking97To0M: 51.1,
        braking161To0M: 127.9,
        zeroTo97S: 8.116,
        zeroTo161S: 22.908,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'mazda-autozam-az-1-pg6sa',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'mazda-autozam-az-1-pg6sa',
      displayName: 'Autozam AZ-1',
      brand: 'Autozam',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['MR', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'F6A',
        culture: 'oddball',
        yearFrom: 1993,
        yearTo: 1993,
        curbWeightKg: 720,
        stockPowerPs: 64,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 64,
        powerRpm: 6500,
        peakTorqueNm: 85,
        torqueRpm: 4000,
        redlineRpm: 7500,
        displacementCc: 657,
        engineConfig: 'I3',
        aspiration: 'turbo',
        weightDistributionFront: 44,
        wheelbaseMm: 2235,
        comHeightMm: 420,
        dragCd: 0.32,
        widthMm: 1395,
        heightMm: 1150,
        stockTyre: '155/65R13',
        tyreCompound: 'eco',
        topSpeedKmh: 189,
        lateralG97: 0.87,
        lateralG193: 0.92,
        braking97To0M: 47.2,
        braking161To0M: 117,
        zeroTo97S: 10.329,
        zeroTo161S: 26.7,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'mazda-rx-7-spirit-r-fd3s',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'mazda-rx-7-spirit-r-fd3s',
      displayName: 'Mazda RX-7 Spirit R (FD3S)',
      brand: 'Mazda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Rotary'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '13B-REW',
        culture: 'oddball',
        yearFrom: 2002,
        yearTo: 2002,
        curbWeightKg: 1270,
        stockPowerPs: 280,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6500,
        peakTorqueNm: 314,
        torqueRpm: 5000,
        redlineRpm: 8000,
        displacementCc: 1308,
        engineConfig: 'rotary-2',
        aspiration: 'twin-turbo',
        weightDistributionFront: 50,
        wheelbaseMm: 2425,
        comHeightMm: 460,
        dragCd: 0.29,
        widthMm: 1760,
        heightMm: 1230,
        stockTyre: '235/45R17',
        tyreCompound: 'sport',
        zeroToHundredS: 5.3,
        topSpeedKmh: 255,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'nissan-silvia-spec-r-s15',
    section: 'Legend',
    inGame: false,
    tierSource: 'assigned',
    model: {
      id: 'nissan-silvia-spec-r-s15',
      displayName: 'Nissan Silvia Spec-R',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'SR20DET',
        culture: 'oddball',
        yearFrom: 2002,
        yearTo: 2002,
        curbWeightKg: 1240,
        stockPowerPs: 253,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 253,
        powerRpm: 6400,
        peakTorqueNm: 278,
        torqueRpm: 4800,
        redlineRpm: 7600,
        displacementCc: 1998,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 51,
        wheelbaseMm: 2525,
        comHeightMm: 450,
        dragCd: 0.301,
        widthMm: 1695,
        heightMm: 1285,
        stockTyre: '205/55R16',
        tyreCompound: 'performance',
        topSpeedKmh: 280,
        lateralG97: 0.92,
        lateralG193: 0.97,
        braking97To0M: 44,
        braking161To0M: 108.1,
        zeroTo97S: 5.45,
        zeroTo161S: 13.957,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  { id: 'nissan-fairlady-z-z32', section: 'Flagship', inGame: true, tierSource: 'in-game' },
  { id: 'toyota-aristo-30v-jzs147', section: 'Flagship', inGame: true, tierSource: 'in-game' },
  {
    id: 'autech-stagea-260rs-wgnc34',
    section: 'Flagship',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'autech-stagea-260rs-wgnc34',
      displayName: 'Nissan Stagea RS Four V',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'RB25DET',
        culture: 'oddball',
        yearFrom: 1997,
        yearTo: 1997,
        curbWeightKg: 1620,
        stockPowerPs: 235,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 235,
        powerRpm: 6000,
        peakTorqueNm: 274,
        torqueRpm: 4800,
        redlineRpm: 7000,
        displacementCc: 2498,
        engineConfig: 'I6',
        aspiration: 'turbo',
        weightDistributionFront: 57,
        wheelbaseMm: 2720,
        comHeightMm: 505,
        dragCd: 0.374,
        widthMm: 1755,
        heightMm: 1510,
        stockTyre: '225/50R17',
        tyreCompound: 'sport',
        topSpeedKmh: 237,
        lateralG97: 0.85,
        lateralG193: 0.86,
        braking97To0M: 46.5,
        braking161To0M: 116.6,
        zeroTo97S: 8.1,
        zeroTo161S: 20.087,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'toyota-altezza-rs200-z-edition-sxe10',
    section: 'Flagship',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'toyota-altezza-rs200-z-edition-sxe10',
      displayName: 'Toyota Altezza RS200 Z Edition',
      brand: 'Toyota',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: '3S-GE BEAMS',
        culture: 'oddball',
        yearFrom: 1999,
        yearTo: 1999,
        curbWeightKg: 1360,
        stockPowerPs: 211,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 211,
        powerRpm: 7600,
        peakTorqueNm: 216,
        torqueRpm: 6400,
        redlineRpm: 7800,
        displacementCc: 1998,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 50,
        wheelbaseMm: 2670,
        comHeightMm: 480,
        dragCd: 0.305,
        widthMm: 1720,
        heightMm: 1410,
        stockTyre: '215/45R17',
        tyreCompound: 'performance',
        topSpeedKmh: 252,
        lateralG97: 0.89,
        lateralG193: 0.91,
        braking97To0M: 45.4,
        braking161To0M: 113.1,
        zeroTo97S: 6.828,
        zeroTo161S: 17.656,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'honda-s2000-ap1',
    section: 'Flagship',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'honda-s2000-ap1',
      displayName: 'Honda S2000',
      brand: 'Honda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'F20C',
        culture: 'oddball',
        yearFrom: 2003,
        yearTo: 2003,
        curbWeightKg: 1250,
        stockPowerPs: 250,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 250,
        powerRpm: 8300,
        peakTorqueNm: 218,
        torqueRpm: 7500,
        redlineRpm: 9000,
        displacementCc: 1997,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 50,
        wheelbaseMm: 2400,
        comHeightMm: 460,
        dragCd: 0.345,
        widthMm: 1750,
        heightMm: 1285,
        stockTyre: '225/50R16',
        tyreCompound: 'sport',
        topSpeedKmh: 264,
        lateralG97: 0.91,
        lateralG193: 0.93,
        braking97To0M: 45.2,
        braking161To0M: 112.2,
        zeroTo97S: 6.124,
        zeroTo161S: 15.331,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
  { id: 'toyota-mr2-sw20', section: 'Flagship', inGame: true, tierSource: 'in-game' },
  { id: 'toyota-mr2-aw11', section: 'Flagship', inGame: true, tierSource: 'in-game' },
  {
    id: 'daihatsu-mira-tr-xx-l70',
    section: 'Kei',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'daihatsu-mira-tr-xx-l70',
      displayName: 'Daihatsu Mira TR-XX (L70)',
      brand: 'Daihatsu',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'entry',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'Turbo', 'Piston', 'Kei'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'EB',
        culture: 'oddball',
        yearFrom: 1985,
        yearTo: 1985,
        curbWeightKg: 570,
        stockPowerPs: 52,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 52,
        powerRpm: 6500,
        peakTorqueNm: 70,
        torqueRpm: 4000,
        redlineRpm: 7000,
        displacementCc: 547,
        engineConfig: 'I3',
        aspiration: 'turbo',
        weightDistributionFront: 62,
        wheelbaseMm: 2250,
        comHeightMm: 520,
        dragCd: 0.4,
        widthMm: 1395,
        heightMm: 1400,
        stockTyre: '145/70R12',
        tyreCompound: 'eco',
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'fr', 'com', 'cd'],
      },
    },
  },
  { id: 'toyota-carina-at150', section: 'Shitbox', inGame: true, tierSource: 'in-game' },
  { id: 'nissan-sunny-b12', section: 'Shitbox', inGame: true, tierSource: 'in-game' },
  {
    id: 'honda-today-jw1',
    section: 'Kei',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'honda-today-jw1',
      displayName: 'Honda Today (JW1)',
      brand: 'Honda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'entry',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'NA', 'Piston', 'Kei'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'E05A',
        culture: 'oddball',
        yearFrom: 1988,
        yearTo: 1988,
        curbWeightKg: 620,
        stockPowerPs: 38,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 38,
        powerRpm: 8000,
        peakTorqueNm: 46,
        torqueRpm: 4500,
        redlineRpm: 8500,
        displacementCc: 547,
        engineConfig: 'I3',
        aspiration: 'NA',
        weightDistributionFront: 60,
        wheelbaseMm: 2330,
        comHeightMm: 530,
        dragCd: 0.35,
        widthMm: 1395,
        heightMm: 1315,
        stockTyre: '145/70R12',
        tyreCompound: 'eco',
        topSpeedKmh: 145,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'fr', 'com', 'cd'],
      },
    },
  },
  {
    id: 'subaru-vivio-rx-r-kk4',
    section: 'Kei',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'subaru-vivio-rx-r-kk4',
      displayName: 'Subaru Vivio RX-R',
      brand: 'Subaru',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'entry',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Supercharged', 'Piston', 'Kei'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'EN07X',
        culture: 'oddball',
        yearFrom: 1994,
        yearTo: 1994,
        curbWeightKg: 760,
        stockPowerPs: 64,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 64,
        powerRpm: 7200,
        peakTorqueNm: 88,
        torqueRpm: 4000,
        redlineRpm: 7800,
        displacementCc: 658,
        engineConfig: 'I4',
        aspiration: 'supercharged',
        weightDistributionFront: 58,
        wheelbaseMm: 2310,
        comHeightMm: 500,
        dragCd: 0.363,
        widthMm: 1395,
        heightMm: 1375,
        stockTyre: '155/65R13',
        tyreCompound: 'eco',
        topSpeedKmh: 171,
        lateralG97: 0.85,
        lateralG193: 0.9,
        braking97To0M: 48.2,
        braking161To0M: 121,
        zeroTo97S: 11.348,
        zeroTo161S: 46.369,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'com'],
      },
    },
  },
  {
    id: 'daihatsu-mira-tr-xx-avanzato-r-l502s',
    section: 'Kei',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'daihatsu-mira-tr-xx-avanzato-r-l502s',
      displayName: 'Daihatsu Mira TR-XX Avanzato R (L502S)',
      brand: 'Daihatsu',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'entry',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FF', 'Turbo', 'Piston', 'Kei'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'JB-JL',
        culture: 'oddball',
        yearFrom: 1995,
        yearTo: 1995,
        curbWeightKg: 710,
        stockPowerPs: 64,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 64,
        powerRpm: 7500,
        peakTorqueNm: 100,
        torqueRpm: 4000,
        redlineRpm: 8000,
        displacementCc: 659,
        engineConfig: 'I4',
        aspiration: 'turbo',
        weightDistributionFront: 60,
        wheelbaseMm: 2300,
        comHeightMm: 510,
        dragCd: 0.33,
        widthMm: 1395,
        heightMm: 1430,
        stockTyre: '155/65R13',
        tyreCompound: 'eco',
        zeroToHundredS: 10.9,
        topSpeedKmh: 150,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['rl', 'fr', 'com', 'cd'],
      },
    },
  },
  {
    id: 'honda-acty-ha4',
    section: 'Kei',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'honda-acty-ha4',
      displayName: 'Honda Acty',
      brand: 'Honda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'entry',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'NA', 'Piston', 'Kei'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'E07A',
        culture: 'oddball',
        yearFrom: 1994,
        yearTo: 1994,
        curbWeightKg: 770,
        stockPowerPs: 38,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 38,
        powerRpm: 5300,
        peakTorqueNm: 54,
        torqueRpm: 4500,
        redlineRpm: 6000,
        displacementCc: 656,
        engineConfig: 'I3',
        aspiration: 'NA',
        weightDistributionFront: 52,
        wheelbaseMm: 1900,
        comHeightMm: 650,
        dragCd: 0.45,
        widthMm: 1395,
        heightMm: 1745,
        stockTyre: '145R12',
        tyreCompound: 'eco',
        topSpeedKmh: 111,
        lateralG97: 0.8,
        lateralG193: 0.8,
        braking97To0M: 49.6,
        zeroTo97S: 24.64,
        measuredFrom: 'forza-panel',
        dataConfidence: 'LOW',
        estimatedFields: ['rl', 'com', 'cd'],
      },
    },
  },
  {
    id: 'suzuki-cappuccino-ea11r',
    section: 'Kei',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'suzuki-cappuccino-ea11r',
      displayName: 'Suzuki Cappuccino (EA11R)',
      brand: 'Suzuki',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'entry',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'Turbo', 'Piston', 'Kei'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'F6A',
        culture: 'oddball',
        yearFrom: 1991,
        yearTo: 1991,
        curbWeightKg: 725,
        stockPowerPs: 64,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 64,
        powerRpm: 6500,
        peakTorqueNm: 85,
        torqueRpm: 4000,
        redlineRpm: 8500,
        displacementCc: 657,
        engineConfig: 'I3',
        aspiration: 'turbo',
        weightDistributionFront: 50,
        wheelbaseMm: 2060,
        comHeightMm: 430,
        dragCd: 0.33,
        widthMm: 1395,
        heightMm: 1185,
        stockTyre: '165/65R14',
        tyreCompound: 'touring',
        zeroToHundredS: 10,
        topSpeedKmh: 150,
        measuredFrom: 'modelled',
        dataConfidence: 'MED',
        estimatedFields: ['com', 'cd', 'z'],
      },
    },
  },
  { id: 'honda-beat-pp1', section: 'Kei', inGame: true, tierSource: 'in-game' },
  {
    id: 'eunos-roadster-na6ce',
    section: 'FR / Drift',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'eunos-roadster-na6ce',
      displayName: 'Mazda MX-5 Miata',
      brand: 'Mazda',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'enthusiast',
      rarity: 'common',
      origin: 'jdm',
      tags: ['FR', 'NA', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'BP-ZE',
        culture: 'oddball',
        yearFrom: 1994,
        yearTo: 1994,
        curbWeightKg: 1057,
        stockPowerPs: 130,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 130,
        powerRpm: 6500,
        peakTorqueNm: 149,
        torqueRpm: 5000,
        redlineRpm: 7000,
        displacementCc: 1839,
        engineConfig: 'I4',
        aspiration: 'NA',
        weightDistributionFront: 51,
        wheelbaseMm: 2265,
        comHeightMm: 460,
        dragCd: 0.426,
        widthMm: 1675,
        heightMm: 1235,
        stockTyre: '185/60R14',
        tyreCompound: 'touring',
        topSpeedKmh: 202,
        lateralG97: 0.84,
        lateralG193: 0.84,
        braking97To0M: 49.7,
        braking161To0M: 123.2,
        zeroTo97S: 8.8,
        zeroTo161S: 25.962,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'nissan-skyline-gt-r-bcnr33',
    section: 'AWD Turbo',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'nissan-skyline-gt-r-bcnr33',
      displayName: 'Nissan Skyline GT-R V-Spec',
      brand: 'Nissan',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'RB26DETT',
        culture: 'oddball',
        yearFrom: 1997,
        yearTo: 1997,
        curbWeightKg: 1540,
        stockPowerPs: 280,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 280,
        powerRpm: 6800,
        peakTorqueNm: 367,
        torqueRpm: 4400,
        redlineRpm: 8000,
        displacementCc: 2568,
        engineConfig: 'I6',
        aspiration: 'twin-turbo',
        weightDistributionFront: 55,
        wheelbaseMm: 2720,
        comHeightMm: 510,
        dragCd: 0.294,
        widthMm: 1780,
        heightMm: 1360,
        stockTyre: '245/45R17',
        tyreCompound: 'sport',
        activeYaw: 'attesa',
        topSpeedKmh: 281,
        lateralG97: 0.91,
        lateralG193: 0.93,
        braking97To0M: 42.5,
        braking161To0M: 106.1,
        zeroTo97S: 5.245,
        zeroTo161S: 12.729,
        measuredFrom: 'forza-panel',
        dataConfidence: 'HIGH',
        estimatedFields: ['com'],
      },
    },
  },
  {
    id: 'subaru-impreza-wrx-sti-gdb',
    section: 'AWD Turbo',
    inGame: false,
    tierSource: 'derived',
    model: {
      id: 'subaru-impreza-wrx-sti-gdb',
      displayName: 'Subaru IMPREZA WRX STI',
      brand: 'Subaru',
      parodyName: 'Research entry',
      parodyBrand: 'Research',
      tier: 'flagship',
      rarity: 'common',
      origin: 'jdm',
      tags: ['AWD', 'Turbo', 'Piston'],
      bookValueYen: 1,
      spec: {
        chassisCode: 'unknown',
        engineCode: 'EJ207',
        culture: 'oddball',
        yearFrom: 2004,
        yearTo: 2004,
        curbWeightKg: 1483,
        stockPowerPs: 282,
        reliabilityBase: 85,
        styleBase: 12,
        styleCeiling: 12,
        aeroCeiling: 1,
        quotedPowerPs: 282,
        powerRpm: 6400,
        peakTorqueNm: 393,
        torqueRpm: 4400,
        redlineRpm: 8000,
        displacementCc: 1994,
        engineConfig: 'flat-4',
        aspiration: 'turbo',
        weightDistributionFront: 58,
        wheelbaseMm: 2525,
        comHeightMm: 530,
        dragCd: 0.37,
        widthMm: 1730,
        heightMm: 1425,
        stockTyre: '225/45R17',
        tyreCompound: 'sport',
        topSpeedKmh: 260,
        lateralG97: 0.91,
        lateralG193: 0.92,
        braking97To0M: 41.9,
        braking161To0M: 105.4,
        zeroTo97S: 4.748,
        zeroTo161S: 12.277,
        measuredFrom: 'forza-panel',
        dataConfidence: 'MED',
        estimatedFields: ['com'],
      },
    },
  },
]
