/**
 * The sale value model, as a runnable artefact.
 *
 * `docs/design/systems/sale-value-system.md` section 9 is GENERATED by this
 * script, and must never be hand-edited. Two review rounds each found the same
 * class of error: a mechanism changed in one section and the worked ledger was
 * not re-run. Computing the table from the levers makes that error impossible.
 *
 * Run:  node tools/sale-value/model.mjs
 *
 * Every value in LEVERS is a PROPOSAL under directive 22. Nothing here reads
 * shipped content, because none of it is signed; when it is, this script is
 * what gets pointed at `economy.json` instead.
 */

// ---------------------------------------------------------------------------
// Levers. All proposed, none signed.
// ---------------------------------------------------------------------------

const LEVERS = {
  marketRepairDiscount: 1.3,
  beyondDiscount: { entry: 0.4, everyday: 0.8, enthusiast: 1.2, flagship: 1.3 },
  aftermarketReturn: { entry: 0.3, everyday: 0.6, enthusiast: 0.9, flagship: 1.0 },

  coherenceDiscountWeight: 0.35,
  retentionFloor: 0.3,
  retentionCeiling: 1.1,

  tasteSpread: 0.12,
  tolerance: { default: 1.0, stancer: 0.0, tuner: 0.5 },

  // One clock, normalised by how often this car is actually seen. An absolute
  // day count double-charges a specialist: liquidity already makes them wait,
  // and an absolute quality slide then taxes the waiting.
  stalenessFloor: 0.35,
  stalenessHalfLifeOffers: 3.5, // in EXPECTED OFFERS, not days
  qualityFresh: 0.98,
  qualityFloor: 0.86,
  qualityHalfLifeOffers: 3.0, // in EXPECTED OFFERS, not days
  qualitySpread: 0.04,
  relistRecovery: 0.7,

  tradeNetwork: 0.87,
  fixer: 0.8,
  salvagePartsCostFactor: 0.78,

  labourSlotsPerDay: 3,
  patienceDays: 60, // hard stop; the player takes the floor rather than hold forever
}

const CHANNELS = {
  shopFront: { ceiling: 1.0, fee: 0 },
  freeAds: { ceiling: 1.05, fee: 1500 },
  magazine: { ceiling: 1.17, fee: 12000 },
  weekendMeet: { ceiling: 1.17, fee: 3000 },
}

// ---------------------------------------------------------------------------
// Seeded RNG. Every roll in this model is reproducible, per the economy-wide
// seeding rule.
// ---------------------------------------------------------------------------

function mulberry32(seed) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function gaussian(rng) {
  const u = Math.max(rng(), 1e-9)
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * rng())
}

const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v))

// ---------------------------------------------------------------------------
// The price stack
// ---------------------------------------------------------------------------

const stageA = (book, mileageFactor, heat) => book * mileageFactor * (heat / 100)

function stageB(clean, billBelow, billAbove, tier) {
  return clean - LEVERS.marketRepairDiscount * billBelow - LEVERS.beyondDiscount[tier] * billAbove
}

function stageC(conditionValue, coherence, tolerance) {
  const discount = LEVERS.coherenceDiscountWeight * (1 - coherence) * tolerance
  return conditionValue * (1 - discount)
}

function stageD(staged, partsValue, coherence, tier, foundation = 1) {
  const retention =
    LEVERS.retentionFloor + (LEVERS.retentionCeiling - LEVERS.retentionFloor) * coherence
  return staged + partsValue * retention * LEVERS.aftermarketReturn[tier] * foundation
}

function channelMultiplier(match, ceiling) {
  const low = 1 - LEVERS.tasteSpread
  const standardTop = 1 + LEVERS.tasteSpread
  if (ceiling > standardTop) return low + (ceiling - low) * match
  return Math.min(low + (standardTop - low) * match, ceiling)
}

// ---------------------------------------------------------------------------
// The listing. Staleness and offer quality both read the SAME normalised
// clock: expected offers seen, not days elapsed.
// ---------------------------------------------------------------------------

function qualityMeanAt(offersSeen) {
  const { qualityFresh, qualityFloor, qualityHalfLifeOffers } = LEVERS
  return qualityFresh - (qualityFresh - qualityFloor) * (1 - Math.exp(-offersSeen / qualityHalfLifeOffers))
}

function stalenessAt(offersSeen) {
  const { stalenessFloor, stalenessHalfLifeOffers } = LEVERS
  return stalenessFloor + (1 - stalenessFloor) * Math.exp(-offersSeen / stalenessHalfLifeOffers)
}

/**
 * Simulate a listing. The player accepts an offer at or above the current
 * expected quality, otherwise waits; at `patienceDays` they take whatever the
 * fast exit pays. Returns the mean accepted quality and mean days to cash.
 */
function simulateListing({ baseOfferRate, seed, trials = 4000 }) {
  const rng = mulberry32(seed)
  let qSum = 0
  let daySum = 0
  let sold = 0
  for (let t = 0; t < trials; t += 1) {
    let offersSeen = 0
    let done = false
    for (let day = 1; day <= LEVERS.patienceDays && !done; day += 1) {
      const rate = baseOfferRate * stalenessAt(offersSeen)
      if (rng() < rate) {
        offersSeen += 1
        const mean = qualityMeanAt(offersSeen - 1)
        const q = clamp(mean + gaussian(rng) * LEVERS.qualitySpread, LEVERS.qualityFloor, 1)
        if (q >= mean) {
          qSum += q
          daySum += day
          sold += 1
          done = true
        }
      }
    }
    if (!done) {
      qSum += LEVERS.tradeNetwork
      daySum += LEVERS.patienceDays
      sold += 1
    }
  }
  return { quality: qSum / sold, days: daySum / sold }
}

// ---------------------------------------------------------------------------
// The car, and the paths
// ---------------------------------------------------------------------------

const S13 = { book: 500000, mileageFactor: 0.925, heat: 100, tier: 'everyday' }
const CLEAN = stageA(S13.book, S13.mileageFactor, S13.heat)

const FD = { book: 1850000, mileageFactor: 0.925, heat: 100, tier: 'enthusiast' }
const FD_CLEAN = stageA(FD.book, FD.mileageFactor, FD.heat)

function listedPath({ name, marketValue, spent, slots, workDays, match, channel, baseOfferRate, seed, note }) {
  const ch = CHANNELS[channel]
  const mult = channelMultiplier(match, ch.ceiling)
  const listing = simulateListing({ baseOfferRate, seed })
  const sale = marketValue * mult * listing.quality - ch.fee
  const profit = sale - spent
  const days = workDays + listing.days
  return {
    name,
    profit,
    perSlot: profit / slots,
    perSlotWeek: profit / (days / 7),
    days,
    quality: listing.quality,
    note,
  }
}

function blindPath({ name, marketValue, spent, slots, workDays, factor, note }) {
  const sale = marketValue * factor
  const profit = sale - spent
  const days = workDays + 1
  return {
    name,
    profit,
    perSlot: profit / slots,
    perSlotWeek: profit / (days / 7),
    days,
    quality: factor,
    note,
  }
}

const paths = []

// Path 0: the repair flip. Broad appeal, many offers, cherry-picked.
{
  const b = stageB(CLEAN, 0, 40000, 'everyday')
  paths.push(
    listedPath({
      name: '0  repair flip',
      marketValue: b,
      spent: 300000 + 60000,
      slots: 8,
      workDays: 3,
      match: 0.6,
      channel: 'shopFront',
      baseOfferRate: 0.55,
      seed: 1995,
      note: 'broad market, clamped at book',
    }),
  )
}

// Path 1: the coherent build. One archetype, rare, pays near the ceiling.
{
  const b = stageB(CLEAN, 0, 40000, 'everyday')
  const d = stageD(stageC(b, 1.0, 1.0), 100000, 1.0, 'everyday')
  paths.push(
    listedPath({
      name: '1  coherent build',
      marketValue: d,
      spent: 300000 + 60000 + 100000,
      slots: 12,
      workDays: 4,
      match: 0.95,
      channel: 'magazine',
      baseOfferRate: 0.12,
      seed: 1996,
      note: 'the racer, and almost nobody else',
    }),
  )
}

// Path 2: the dodgy build. The stancer, or the dump.
{
  const b = stageB(CLEAN, 0, 40000, 'everyday')
  const coherence = 0.605
  const stancerBase = stageD(stageC(b, coherence, LEVERS.tolerance.stancer), 93600, coherence, 'everyday')
  const marketBase = stageD(stageC(b, coherence, LEVERS.tolerance.default), 93600, coherence, 'everyday')
  paths.push(
    listedPath({
      name: '2  dodgy build, sold',
      marketValue: stancerBase,
      spent: 300000 + 60000 + 93600,
      slots: 9,
      workDays: 3,
      match: 0.9,
      channel: 'weekendMeet',
      baseOfferRate: 0.06,
      seed: 1997,
      note: 'the stancer alone, tolerance 0',
    }),
  )
  paths.push(
    blindPath({
      name: '2  dodgy build, dumped',
      marketValue: marketBase,
      spent: 300000 + 60000 + 93600,
      slots: 9,
      workDays: 3,
      factor: LEVERS.tradeNetwork,
      note: 'taste-blind, default tolerance',
    }),
  )
}

// Path 3: the salvage flip. A yen of parts clears a yen of bill.
{
  const billAtPurchase = 180000
  const cleared = 70000
  const b = stageB(CLEAN, billAtPurchase - cleared, 40000, 'everyday')
  paths.push(
    blindPath({
      name: '3  salvage, network',
      marketValue: b,
      spent: 100000 + cleared,
      slots: 12,
      workDays: 4,
      factor: LEVERS.tradeNetwork,
      note: 'better cash',
    }),
  )
  paths.push(
    blindPath({
      name: '3  salvage, fixer',
      marketValue: b,
      spent: 100000 + cleared,
      slots: 12,
      workDays: 4,
      factor: LEVERS.fixer,
      note: 'worse cash, buys favour',
    }),
  )
  paths.push(
    blindPath({
      name: '3  salvage, harvested',
      marketValue: b,
      spent: 100000 + cleared * LEVERS.salvagePartsCostFactor,
      slots: 13,
      workDays: 5,
      factor: LEVERS.tradeNetwork,
      note: 'a good route through the yard, one extra visit day',
    }),
  )
}

// Path 4: the restoration house. Enthusiast tier, where beyondDiscount is 1.2
// and work past the expected band actually returns something.
{
  const b = stageB(FD_CLEAN, 0, 0, 'enthusiast')
  paths.push(
    listedPath({
      name: '4  restoration',
      marketValue: b,
      spent: 1150000 + 210000 + 260000,
      slots: 26,
      workDays: 9,
      match: 0.92,
      channel: 'magazine',
      baseOfferRate: 0.1,
      seed: 1998,
      note: 'FD3S to mint, collector',
    }),
  )
}

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

const yen = (n) => Math.round(n).toLocaleString('en-GB')
const pad = (s, n) => String(s).padEnd(n)
const padL = (s, n) => String(s).padStart(n)

console.log(`Clean value, S13:  ${yen(CLEAN)}`)
console.log(`Clean value, FD3S: ${yen(FD_CLEAN)}`)
console.log()
console.log('| path | profit | per slot | per slot-week | days | E[quality] |')
console.log('| --- | ---: | ---: | ---: | ---: | ---: |')
for (const p of paths) {
  console.log(
    `| ${pad(p.name, 22)} | ${padL(yen(p.profit), 9)} | ${padL(yen(p.perSlot), 7)} | ${padL(yen(p.perSlotWeek), 8)} | ${padL(p.days.toFixed(1), 5)} | ${padL(p.quality.toFixed(3), 6)} |`,
  )
}
console.log()
for (const p of paths) console.log(`${pad(p.name, 22)}  ${p.note}`)
